### ISSUE TITLE
lmdb: ['custom:OpenLDAP']

### ISSUE THREAD

**Issue by ChALkeR** [orospakr/vrms-arch#16]
See https://www.gnu.org/licenses/license-list.html#newOpenLDAP

lmdb uses v2.8, but the differences are most likely very minor there.

**Comment by orospakr** [comment]
resolved

**Comment by ChALkeR** [comment]
Yay!

**Comment by hyc** [comment]
@ChALkeR two words changed in clause 1. The rest is spacing.
http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=commitdiff;h=eb7ff29a0dbe8596530d2ec980920ca3472d1520
